### PR TITLE
[as2_platform_dji_osdk] publishing gimbal attitude at any cb hit

### PR DESCRIPTION
**Pull request by pariaspe**
## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Issue(s) this addresses   | #411 |
| ROS2 version tested on | Humble |
| Aerial platform tested on | - |

---

## Description of contribution in a few bullet points

* publising gimbal attitude at any cb hit

### CODE REVIEW

**Comment by miferco97** [comment]
@pariaspe what is the status of this ?

**Comment by RPS98** [comment]
> > @pariaspe what is the status of this ?
> 
> Not sure, @RPS98 might have a better understanding about it

Not tested yet

**Comment by miferco97** [comment]
We shall move this into the [aerostack2/as2_platform_dji_osdk](https://github.com/aerostack2/as2_platform_dji_osdk) repo

**Comment by miferco97** [comment]
This has been moved into https://github.com/aerostack2/as2_platform_dji_osdk/pull/1

**Pull request closed without merging**
