### PR TITLE
IGN_GAZEBO_RESOURCE_PATH changed to GZ_SIM_RESOURCE_PATH

### PR DESCRIPTION
**Pull request by javilinos**
…RCE_PATH

---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Issue(s) this addresses   | #485 |
| ROS2 version tested on |Humble|
| Aerial platform tested on | Gazebo (Harmonic)|

---

## Description of contribution in a few bullet points

* IGN_GAZEBO_RESOURCE_PATH changed to GZ_SIM_RESOURCE_PATH
* Gazebo Harmonic works now

### CODE REVIEW

**Review by RPS98 — COMMENTED** [review]
Have you try this on fortress?

**Comment by javilinos** [comment]
> Have you try this on fortress?

shouldn't work on fortress, we either choose one to use or we can add aditional ```resource_path_ign = os.environ.get('IGN_GAZEBO_RESOURCE_PATH')``` along side ```resource_path_gz = os.environ.get('GZ_SIM_RESOURCE_PATH')``` 
what do you think? @pariaspe

**Review by RPS98 — APPROVED** [review]

**Comment by javilinos** [comment]
> > Have you try this on fortress?
> 
> shouldn't work on fortress, we either choose one to use or we can add aditional `resource_path_ign = os.environ.get('IGN_GAZEBO_RESOURCE_PATH')` along side `resource_path_gz = os.environ.get('GZ_SIM_RESOURCE_PATH')` what do you think? @pariaspe

It DOES work on fortress [Fortress update](https://github.com/gazebosim/gz-sim/commit/45a01a86e96b981f83d0a87a2c03a95dba2d8788)

**Review by pariaspe — APPROVED** [review]

**Comment by javilinos** [comment]
> > It DOES work on fortress [Fortress update](https://github.com/gazebosim/gz-sim/commit/45a01a86e96b981f83d0a87a2c03a95dba2d8788)
> 
> Has this been tested by you @javilinos ???

No. Tested by @RPS98 with our docker.

**Comment by keikei014** [comment]
@javilinos it is not working on Fortress on my system

**Comment by javilinos** [comment]
> @javilinos it is not working on Fortress on my system

Please provide logs. Thanks.

**Pull request merged**
