### PR TITLE
[as2_gazebo_assets] Fix model templates for sensor naming

### PR DESCRIPTION
**Pull request by fjanguita**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Issue(s) this addresses   |  |
| ROS2 version tested on | Humble |
| Aerial platform tested on | Gazebo |

---

## Description of contribution in a few bullet points

* Jinja templates fixed to support different naming for sensors.
* Variable naming enhanced for better readability.

## Description of documentation updates required from your changes

---

## Future work that may be required in bullet points

* Fix bridge topics construction to support changes in gimbal name.

### CODE REVIEW

**Review by pariaspe — CHANGES_REQUESTED** [review]
Sensor type and sensor name seems to be swapped. 

```bash
$ ros2 topic info -v /drone0/sensor_measurements/hd_camera/image_raw
Type: sensor_msgs/msg/Image

Publisher count: 2

Node name: ros_gz_bridge
Node namespace: /drone0
Topic type: sensor_msgs/msg/Image
Endpoint type: PUBLISHER
GID: 01.10.4d.23.f3.42.7c.c2.96.4e.76.1a.00.00.1c.03.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (10)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Node name: ros_gz_bridge
Node namespace: /drone0
Topic type: sensor_msgs/msg/Image
Endpoint type: PUBLISHER
GID: 01.10.4d.23.f3.42.7c.c2.96.4e.76.1a.00.00.1e.03.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (10)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Subscription count: 1

Node name: rviz
Node namespace: /
Topic type: sensor_msgs/msg/Image
Endpoint type: SUBSCRIPTION
GID: 01.10.be.c9.cf.35.e2.30.3f.cf.94.6a.00.00.26.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (5)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite
```
There are two bridges publishing over the same topic since they are using `model_type` for ros topic construction.

This is the simulation description file I'm using:
```json
{
    "world_name": "empty",
    "drones": [
        {
            "model_type": "quadrotor_base",
            "model_name": "drone0",
            "xyz": [ 1.0, 1.0, 0.3 ],
            "rpy": [ 0, 0, 0.0 ],
            "payload": [
                {
                    "model_name": "front_camera",
                    "model_type": "hd_camera"
                },
                {
                    "model_name": "ventral_camera",
                    "model_type": "hd_camera",
                    "rpy": [ 0, 1.57, 0.0 ]
                }
            ]
        }
    ]
}
```

**Review by RPS98 — APPROVED** [review]

**Comment by fjanguita** [comment]
@pariaspe @RPS98 with the last changes, two GPS sensors on the same drone will still publish on the same topic. it is not a likely case but just for you to know

**Comment by pariaspe** [comment]
> @pariaspe @RPS98 with the last changes, two GPS sensors on the same drone will still publish on the same topic. it is not a likely case but just for you to know

Why gps sensor is different from the other sensors?

**Comment by pariaspe** [comment]
> right now a custom gps_bridge is being used, and it takes the gps sensor topic from as2_core::names::topics::gps which is always {drone_name}/sensor_measurements/gps

Alright, good to know. We should this known issues somewhere (together with gimbal_name forced to be "gimbal").  Anyway, I'm sorry to say that it is still failing when using gimbal + any payload with different model_name from model_type. Check gazebo traceback:
 ```bash
[ruby $(which gz) sim-1] [Err] [UserCommands.cc:1145] Error Code 20: Msg: Child frame with name[gimbal::_0::_1::_2::gb_cam::gb_cam] specified by joint with name[gb_cam_joint] not found in model with name[drone0].
[ruby $(which gz) sim-1] [Err] [UserCommands.cc:1145] Error Code 25: Msg: FrameAttachedToGraph error, Non-LINK vertex with name [drone0::gb_cam_joint] is disconnected; it should have 1 outgoing edge in MODEL attached_to graph.
[ruby $(which gz) sim-1] [Err] [UserCommands.cc:1145] Error Code 25: Msg: Graph has __model__ scope but sink vertex named [drone0::gb_cam_joint] does not have FrameType LINK or STATIC_MODEL when starting from vertex with name [drone0::gb_cam_joint].
[ruby $(which gz) sim-1] [Err] [UserCommands.cc:1145] Error Code 26: Msg: relative_to name[gimbal::_0::_1::_2::gb_cam::gb_cam] specified by joint with name[gb_cam_joint] does not match a nested model, link, joint, or frame name in model with name[drone0].
[ruby $(which gz) sim-1] [Err] [UserCommands.cc:1145] Error Code 28: Msg: PoseRelativeToGraph error, Vertex with name [drone0::gb_cam_joint] is disconnected; it should have 1 incoming edge in MODEL relative_to graph.
[ruby $(which gz) sim-1] [Err] [UserCommands.cc:1145] Error Code 28: Msg: PoseRelativeToGraph unable to find path to source vertex when starting from vertex with id [19].
[ruby $(which gz) sim-1] [Err] [UserCommands.cc:1145] Error Code 20: Msg: child frame with name[gimbal::_0::_1::_2::gb_cam::gb_cam] specified by joint with name[gb_cam_joint] not found in model with name[drone0].
[ruby $(which gz) sim-1] [Err] [UserCommands.cc:1145] Error Code 23: Msg: FrameAttachedToGraph unable to find unique frame with name [gimbal::_0::_1::_2::gb_cam::gb_cam] in graph.
```

This is the simulation description file I'm using this time:
```json
{
    "world_name": "empty",
    "drones": [
        {
            "model_type": "quadrotor_base",
            "model_name": "drone0",
            "xyz": [ 1.0, 1.0, 3 ],
            "rpy": [ 0.0, 0.0, 0.0 ],
            "flight_time": 60,
            "payload": [
                {
                    "model_name": "gimbal",
                    "model_type": "gimbal_position",
                    "payload": {
                        "model_name": "gb_cam",
                        "model_type": "hd_camera"
                    }
                }
            ]
        }
    ]
}
```

**Review by pariaspe — APPROVED** [review]

**Pull request merged**
