### PR TITLE
follow reference with reference facing added

### PR DESCRIPTION
**Pull request by javilinos**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Issue(s) this addresses   | #272 |
| ROS2 version tested on | Humble|
| Aerial platform tested on |Ignition|

---

## Description of contribution in a few bullet points

* Follow reference now admits reference facing mode.

## Description of documentation updates required from your changes

* New yaw mode: REFERENCE_FACING

---

### CODE REVIEW

**Comment by RPS98** [comment]
I believe that what we are doing is path facing.  The drone will move towards the reference ("path) looking at the reference ("facing"). In other behaviors such as Go To, it works the same, the drone looks at the reference. The importance of path facing, especially in the follow reference behavior, is that the drone looks at the reference so as not to lose it in the image.

**Comment by javilinos** [comment]
@RPS98 when doing a 'Go_to' in earth frame with path facing the drone is not looking at the reference (which would be 0,0 of earth frame), instead it is looking at the motion/velocity vector which is the same as looking as the position set in 'Go_to' argument in respect of earth frame. In this case it is true that we are not interested in the drone looking at the motion vector as we always want to look at the 0,0 of our reference, but issue #194 suggest that in the future we might want to, for example, orbit a reference with the drone x axis aligned with the motion vector (path_facing) or looking at the 0,0 of the reference (reference_facing).

**Comment by RPS98** [comment]
I think the best way is to follow these steps:

Create a Pull Request to add the new Yaw Mode:

1. Add Yaw Mode: `YAW_TO_REFERENCE`

2. Now, behaviors as Go To use Path Facing, but they really use Yaw To Reference. So, we have to change the behavior to use the new mode.
  2.1 Change behaviors
  2.2 Change python interface
  2.3 Check Keyboard Teleop
  2.4 Check missions. I think that missions are not affected by this change

Then, use this Pull Request to add the new Yaw Mode to the Follow Reference behavior.

What do you think @javilinos ?

**Comment by javilinos** [comment]
Seems good to me, I'm on it @RPS98

**Review by pariaspe — APPROVED** [review]

**Review by RPS98 — APPROVED** [review]

**Pull request merged**
